<?php

use Illuminate\Database\Seeder;
use App\Customer;

class CustomersTableSeeder extends Seeder
{
    protected $customers = [
        [
            '298857',
            'JAZLYN CARTAGENA',
            '',
            'JAZLYN',
            'CARTAGENA',
            '160 MENAHAN STREET APT6B',
            '',
            'BROOKLYN',
            'NY',
            'US United States',
            '11221-3948',
            '3479905777',
            '',
            'JAZLYN',
            'CARTAGENA',
            '160 MENAHAN STREET APT6B',
            '',
            'BROOKLYN',
            'NY',
            'US United States',
            '11221',
            '3479905777',
        ],
        [
            '298842',
            'Michelle Crawford',
            '',
            'Michelle',
            'Crawford',
            '7115 Chapparal Dr',
            '',
            'District Heights',
            'MD',
            'US United States',
            '20747-1771',
            '3013506102',
            '',
            'Michelle',
            'Crawford',
            '7115 Chapparal Dr',
            '',
            'District Heights',
            'MD',
            'US United States',
            '20747',
            '3013506102',
        ],
        [
            '281461',
            'Alena Safonova',
            '',
            'Alena',
            'Safonova',
            '3811 Fishing Trail',
            '',
            'Sarasota',
            'FL',
            'US United States',
            '34235-4640',
            '9419622835',
            '',
            'Alena',
            'Safonova',
            '3811 Fishing Trail',
            '',
            'Sarasota',
            'FL',
            'US United States',
            '34235',
            '9419622835',
        ],
        [
            '228469',
            'Colleen Avila',
            '',
            'Colleen',
            'Avila',
            '11932 Wild Goose St',
            '',
            'Garden Grove',
            'CA',
            'US United States',
            '92845-1436',
            '(714) 349-2090',
            '',
            'Colleen',
            'Avila',
            '11932 Wild Goose St',
            '',
            'Garden Grove',
            'CA',
            'US United States',
            '92845',
            '(714) 349-2090',
        ],
        [
            '298858',
            'Lupe Morgan',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510-3666',
            '707.745.8859',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510',
            '707.745.8859',
        ],
        [
            '298859',
            'Marcia Houck - Greene',
            '',
            'Marcia Houck -',
            'Greene',
            '1575 West Street Road',
            'Apt. 233',
            'Warminster',
            'PA',
            'US United States',
            '18974-3145',
            '2155121932',
            '',
            'Marcia R.',
            'Houck',
            '1575 West Street Road',
            'Apt. 233',
            'Warminster',
            'PA',
            'US United States',
            '18974',
            '2155121932',
        ],
        [
            '298860',
            'Marie Embry',
            '',
            'Marie',
            'Embry',
            '5149 Pecan Drive',
            '',
            'Ypsilanti',
            'MI',
            'US United States',
            '48197-6819',
            '734-434-0460',
            '',
            'Marie',
            'Embry',
            '5149 Pecan Drive',
            '',
            'Ypsilanti',
            'MI',
            'US United States',
            '48197',
            '734-434-0460',
        ],
        [
            '297542',
            'Parvaneh Amirahmadi',
            '',
            'Parvaneh',
            'Amirahmadi',
            '1879 Cedaridge Cir',
            '',
            'Superior',
            'CO',
            'US United States',
            '80027-8090',
            '7205327580',
            '',
            'Parvaneh',
            'Amirahmadi',
            '1879 Cedaridge Cir',
            '',
            'Superior',
            'CO',
            'US United States',
            '80027',
            '7205327580',
        ],
        [
            '298860',
            'Marie Embry',
            '',
            'Marie',
            'Embry',
            '5149 Pecan Drive',
            '',
            'Ypsilanti',
            'MI',
            'US United States',
            '48197-6819',
            '734-434-0460',
            '',
            'Marie',
            'Embry',
            '5149 Pecan Drive',
            '',
            'Ypsilanti',
            'MI',
            'US United States',
            '48197',
            '734-434-0460',
        ],
        [
            '298862',
            'Stacy Yarbrough',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341-2628',
            '4044575457',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341',
            '4044575457',
        ],
        [
            '39652',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            'NEW YORK',
            'US United States',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            'US United States',
            '',
            '',
        ],
        [
            '298861',
            'Marian Wu',
            '',
            'Marian',
            'Wu',
            '2310 41st Ave',
            '9E',
            'Long Island City',
            'NY',
            'US United States',
            '11101-3950',
            '9174760803',
            '',
            'Marian',
            'Wu',
            '2310 41st Ave',
            '9E',
            'Long Island City',
            'NY',
            'US United States',
            '11101',
            '9174760803',
        ],
        [
            '298846',
            'Tiana Henriks',
            '',
            'Tiana',
            'Henriks',
            '29191 Country Hills Road',
            '',
            'San Juan Capistrano',
            'CA',
            'US United States',
            '92675-1026',
            '9496063998',
            '',
            'Tiana',
            'Henriks',
            '29191 Country Hills Road',
            '',
            'San Juan Capistrano',
            'CA',
            'US United States',
            '92675',
            '9496063998',
        ],
        [
            '298858',
            'Lupe Morgan',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510-3666',
            '707.745.8859',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510',
            '707.745.8859',
        ],
        [
            '298835',
            'Mary Leigh Newsom',
            '',
            'Mary Leigh',
            'Newsom',
            '104 Beacon Ct.',
            '',
            'Smyrna',
            'TN',
            'US United States',
            '37167-8435',
            '615-462-7722',
            '',
            'Mary Leigh',
            'Newsom',
            '104 Beacon Ct.',
            '',
            'Smyrna',
            'TN',
            'US United States',
            '37167',
            '615-462-7722',
        ],
        [
            '298863',
            'Teller',
            '',
            'Teller',
            '',
            '166 Forest Hill Rd',
            '',
            'West Orange',
            'NJ',
            'US United States',
            '07052-3958',
            '9736698210',
            '',
            'Ethan',
            'Teller',
            '9015 Burroughs Rd',
            '',
            'Los Angeles',
            'CA',
            'US United States',
            '90046',
            '8184399893',
        ],
        [
            '298862',
            'Stacy Yarbrough',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341-2628',
            '4044575457',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341',
            '4044575457',
        ],
        [
            '298576',
            'Shelly Alanis',
            '',
            'Shelly',
            'Alanis',
            '8409 Florida Court',
            '',
            'Sacramento',
            'CA',
            'US United States',
            '95826-3016',
            '9167478844',
            '',
            'Shelly',
            'Alanis',
            '8409 Florida Court',
            '',
            'Sacramento',
            'CA',
            'US United States',
            '95826',
            '9167478844',
        ],
        [
            '298864',
            'Melanie Gonzalez',
            '',
            'Melanie',
            'Gonzalez',
            '20477 Willowmere Ct.',
            '',
            'Sterling',
            'VA',
            'US United States',
            '20165-7570',
            '7034301570',
            '',
            'Melanie',
            'Gonzalez',
            '20477 Willowmere Ct.',
            '',
            'Sterling',
            'VA',
            'US United States',
            '20165',
            '7034301570',
        ],
        [
            '298865',
            'Laura A Molina',
            '',
            'Laura A',
            'Molina',
            '220 East 53rd Street',
            'Apt. 3A',
            'New York',
            'NY',
            'US United States',
            '10022-5225',
            '5166333049',
            '',
            'Laura A',
            'Molina',
            '220 East 53rd Street',
            'Apt. 3A',
            'New York',
            'NY',
            'US United States',
            '10022',
            '5166333049',
        ],
        [
            '298862',
            'Stacy Yarbrough',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341-2628',
            '4044575457',
            '',
            'Stacy',
            'Yarbrough',
            '2351 Johnson Ferry Rd Ne',
            '',
            'Atlanta',
            'GA',
            'US United States',
            '30341',
            '4044575457',
        ],
        [
            '298838',
            'Donna Summers',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074-9223',
            '7409652132',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074',
            '7409652132',
        ],
        [
            '298866',
            'Jessica Lagona',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095-2304',
            '210-621-3736',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095',
            '210-621-3736',
        ],
        [
            '298866',
            'Jessica Lagona',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095-2304',
            '210-621-3736',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095',
            '210-621-3736',
        ],
        [
            '298867',
            'Anthony Breen',
            '',
            'Anthony',
            'Breen',
            '11 Phillips Street',
            'Apt 8',
            'Boston',
            'MA',
            'US United States',
            '02114-3724',
            '6153973827',
            '',
            'Elta',
            'Mariani',
            '',
            '',
            '',
            '',
            '',
            '',
            '615-397-3827',
        ],
        [
            '298858',
            'Lupe Morgan',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510-3666',
            '707.745.8859',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510',
            '707.745.8859',
        ],
        [
            '298835',
            'Mary Leigh Newsom',
            '',
            'Mary Leigh',
            'Newsom',
            '104 Beacon Ct.',
            '',
            'Smyrna',
            'TN',
            'US United States',
            '37167-8435',
            '615-462-7722',
            '',
            'Mary Leigh',
            'Newsom',
            '104 Beacon Ct.',
            '',
            'Smyrna',
            'TN',
            'US United States',
            '37167',
            '615-462-7722',
        ],
        [
            '298868',
            'Allison Schneider',
            '',
            'Allison',
            'Schneider',
            '8 The Oaks',
            '',
            'Roslyn',
            'NY',
            'US United States',
            '11576-1726',
            '5167101252',
            '',
            'Allison',
            'Schneider',
            '8 The Oaks',
            '',
            'Roslyn',
            'NY',
            'US United States',
            '11576',
            '5167101252',
        ],
        [
            '298872',
            'Monique Campbell',
            '',
            'Monique',
            'Campbell',
            '3531 Stonecreek Place',
            '',
            'Helena',
            'AL',
            'US United States',
            '35080-8007',
            '2056023859',
            '',
            'Monique',
            'Campbell',
            '3531 Stonecreek Place',
            '',
            'Helena',
            'AL',
            'US United States',
            '35080',
            '2056023859',
        ],
        [
            '298869',
            'Nicolette Comer',
            '',
            'Nicolette',
            'Comer',
            '40 Lincoln Ave',
            'Apt G1',
            'Pelham',
            'NY',
            'US United States',
            '10803-1129',
            '5105424291',
            '',
            'Nicolette',
            'Comer',
            '40 Lincoln Ave',
            'Apt G1',
            'Pelham',
            'NY',
            'US United States',
            '10803',
            '5105424291',
        ],
        [
            '298871',
            'James Cervasi',
            '',
            'James',
            'Cervasi',
            '54 W. 4th Street',
            'Apt 1',
            'Nazareth',
            'PA',
            'US United States',
            '18064',
            '610-365-8889',
            '',
            'James',
            'Cervasi',
            '54 W. 4th Street',
            'Apt 1',
            'Nazareth',
            'PA',
            'US United States',
            '18064',
            '610-365-8889',
        ],
        [
            '298870',
            'Jantrice Foster',
            '',
            'Jantrice',
            'Foster',
            '3637 Log Trail Dr Apt J',
            '',
            'Bham',
            'AL',
            'US United States',
            '35216-6031',
            '2056013653',
            '',
            'Jantrice',
            'Foster',
            '3637 Log Trail Dr Apt J',
            '',
            'B\'ham',
            'AL',
            'US United States',
            '35216',
            '2056013653',
        ],
        [
            '298858',
            'Lupe Morgan',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510-3666',
            '707.745.8859',
            '',
            'Lupe',
            'Morgan',
            '815 Campas Ct',
            '',
            'Benicia',
            'CA',
            'US United States',
            '94510',
            '707.745.8859',
        ],
        [
            '298866',
            'Jessica Lagona',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095-2304',
            '210-621-3736',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095',
            '210-621-3736',
        ],
        [
            '298866',
            'Jessica Lagona',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095-2304',
            '210-621-3736',
            '',
            'Jessica',
            'Lagona',
            '242 S. 8th Street',
            '',
            'Wood River',
            'IL',
            'US United States',
            '62095',
            '210-621-3736',
        ],
        [
            '298873',
            'Ivan Holeman',
            '',
            'Ivan',
            'Holeman',
            '333 Nw 9th Ave',
            'Unit 1310',
            'Portland',
            'OR',
            'US United States',
            '97209-3349',
            '5038303965',
            '',
            'Ivan',
            'Holeman',
            '333 Nw 9th Ave',
            'Unit 1310',
            'Portland',
            'OR',
            'US United States',
            '97209',
            '5038303965',
        ],
        [
            '272227',
            'Nicole Yamada',
            '',
            'Nicole',
            'Yamada',
            '333 Lakeside Dr',
            '',
            'Foster CIty',
            'CA',
            'US United States',
            '94404-1147',
            '4088320324',
            '',
            'Nicole',
            'Yamada',
            '419 Kuehnis Dr.',
            '',
            'Campbell',
            'CA',
            'US United States',
            '95008',
            '4088320324',
        ],
        [
            '298874',
            'Nikita Schellhardt',
            '',
            'Nikita',
            'Schellhardt',
            '12479 Mustone Ln. Apt 101',
            '',
            'St Louis',
            'MO',
            'US United States',
            '63146-2854',
            '618-789-1552',
            '',
            'Nikita',
            'Schellhardt',
            '12479 Mustone Ln. Apt 101',
            '',
            'St Louis',
            'MO',
            'US United States',
            '63146',
            '618-789-1552',
        ],
        [
            '298874',
            'Nikita Schellhardt',
            '',
            'Nikita',
            'Schellhardt',
            '12479 Mustone Ln. Apt 101',
            '',
            'St Louis',
            'MO',
            'US United States',
            '63146-2854',
            '618-789-1552',
            '',
            'Nikita',
            'Schellhardt',
            '12479 Mustone Ln. Apt 101',
            '',
            'St Louis',
            'MO',
            'US United States',
            '63146',
            '618-789-1552',
        ],
        [
            '298875',
            'Christina Marie Soriano',
            '',
            'Christina Marie',
            'Soriano',
            '12335 Sweetgum Dr',
            '',
            'Rancho Cucamonga',
            'CA',
            'US United States',
            '91739-1635',
            '9096609082',
            '',
            'Christina Marie',
            'Soriano',
            '12335 Sweetgum Dr',
            '',
            'Rancho Cucamonga',
            'CA',
            'US United States',
            '91739',
            '9096609082',
        ],
        [
            '298576',
            'Shelly Alanis',
            '',
            'Shelly',
            'Alanis',
            '8409 Florida Court',
            '',
            'Sacramento',
            'CA',
            'US United States',
            '95826-3016',
            '9167478844',
            '',
            'Shelly',
            'Alanis',
            '8409 Florida Court',
            '',
            'Sacramento',
            'CA',
            'US United States',
            '95826',
            '9167478844',
        ],
        [
            '297674',
            'Monty Robinson',
            '',
            'Monty',
            'Robinson',
            '1715 Kresler Pl',
            '',
            'Chesapeake',
            'VA',
            'US United States',
            '23324-1308',
            '7575372578',
            '',
            'Monty',
            'Robinson',
            '1715 Kresler Pl',
            '',
            'Chesapeake',
            'VA',
            'US United States',
            '23324-1308',
            '7575372578',
        ],
        [
            '298838',
            'Donna Summers',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074-9223',
            '7409652132',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074',
            '7409652132',
        ],
        [
            '298876',
            'Andrew Strobusch',
            '',
            'Andrew',
            'Strobusch',
            '1027 Riverside Dr Apt A',
            '',
            'Waupaca',
            'WI',
            'US United States',
            '54981-1975',
            '7152813134',
            '',
            'Andrew',
            'Strobusch',
            '208 1/2 8th Ave',
            '',
            'Antigo',
            'WI',
            'US United States',
            '54409',
            '7152813134',
        ],
        [
            '298877',
            'Gloria Chiucchi',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705-1531',
            '5708232557',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705',
            '5708232557',
        ],
        [
            '298878',
            'TAMMIE CRAFTON',
            '',
            'TAMMIE',
            'CRAFTON',
            '2003 Bayview Dr',
            '',
            'Fritch',
            'TX',
            'US United States',
            '79036-8606',
            '806-857-5424',
            '',
            'TAMMIE',
            'CRAFTON',
            '2003 Bayview Dr',
            '',
            'Fritch',
            'TX',
            'US United States',
            '79036-8606',
            '806-857-5424',
        ],
        [
            '298873',
            'Ivan Holeman',
            '',
            'Ivan',
            'Holeman',
            '333 Nw 9th Ave',
            'Unit 1310',
            'Portland',
            'OR',
            'US United States',
            '97209-3349',
            '5038303965',
            '',
            'Ivan',
            'Holeman',
            '333 Nw 9th Ave',
            'Unit 1310',
            'Portland',
            'OR',
            'US United States',
            '97209',
            '5038303965',
        ],
        [
            '298879',
            'Marc San Juan',
            '',
            'Marc San',
            'Juan',
            '4318 Merced Ave.',
            '',
            'Baldwin Park',
            'CA',
            'US United States',
            '91706-2961',
            '6263767911',
            '',
            'Marc San',
            'Juan',
            '4318 Merced Ave.',
            '',
            'Baldwin Park',
            'CA',
            'US United States',
            '91706',
            '6263767911',
        ],
        [
            '298880',
            'Jean Schebe',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '07013-2695',
            '2015751443',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '7013',
            '2015751443',
        ],
        [
            '298838',
            'Donna Summers',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074-9223',
            '7409652132',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074',
            '7409652132',
        ],
        [
            '298881',
            'Roberto Chavez',
            '',
            'Roberto',
            'Chavez',
            '196 Eagle Ct',
            '',
            'Woodstock',
            'GA',
            'US United States',
            '30188-3808',
            '7703801584',
            '',
            'Roberto',
            'Chavez',
            '196 Eagle Ct',
            '',
            'Woodstock',
            'GA',
            'US United States',
            '30188',
            '7703801584',
        ],
        [
            '298882',
            'Ann Kahn',
            '',
            'Ann',
            'Kahn',
            '5713 Candlewood St',
            '',
            'Lakewood',
            'CA',
            'US United States',
            '90713-1827',
            '562-335-2077',
            '',
            'Ann',
            'Kahn',
            '5713 Candlewood St',
            '',
            'Lakewood',
            'CA',
            'US United States',
            '90713',
            '562-335-2077',
        ],
        [
            '298883',
            'Bu',
            '',
            'Bu',
            '',
            'S74w14235 settler Way',
            '',
            'MUSKEGO',
            'WI',
            'US United States',
            '53150',
            '4144229474',
            '',
            'Bu',
            '',
            'S74w14235 settler Way',
            '',
            'MUSKEGO',
            'WI',
            'US United States',
            '53150',
            '4144229474',
        ],
        [
            '298877',
            'Gloria Chiucchi',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705-1531',
            '5708232557',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705',
            '5708232557',
        ],
        [
            '298884',
            'Carolyn Bachman',
            '',
            'Carolyn',
            'Bachman',
            '6 Green Tree Dr',
            '',
            'West Chester',
            'PA',
            'US United States',
            '19382-8477',
            '6105056503',
            '',
            'Carolyn',
            'Bachman',
            '6 Green Tree Dr',
            '',
            'West Chester',
            'PA',
            'US United States',
            '19382-8477',
            '6105056503',
        ],
        [
            '298884',
            'Carolyn Bachman',
            '',
            'Carolyn',
            'Bachman',
            '6 Green Tree Dr',
            '',
            'West Chester',
            'PA',
            'US United States',
            '19382-8477',
            '6105056503',
            '',
            'Carolyn',
            'Bachman',
            '6 Green Tree Dr',
            '',
            'West Chester',
            'PA',
            'US United States',
            '19382-8477',
            '6105056503',
        ],
        [
            '298877',
            'Gloria Chiucchi',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705-1531',
            '5708232557',
            '',
            'Gloria',
            'Chiucchi',
            '36 West Carey Street',
            '',
            'Plains',
            'PA',
            'US United States',
            '18705',
            '5708232557',
        ],
        [
            '298885',
            'Abena KaDumasane',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218-2001',
            '6156095514',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218',
            '6156095514',
        ],
        [
            '298885',
            'Abena KaDumasane',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218-2001',
            '6156095514',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218',
            '6156095514',
        ],
        [
            '298885',
            'Abena KaDumasane',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218-2001',
            '6156095514',
            '',
            'Abena',
            'KaDumasane',
            '3905 Flicker Dr',
            '',
            'Nashville',
            'TN',
            'US United States',
            '37218',
            '6156095514',
        ],
        [
            '298886',
            'Lacey Puckett',
            '',
            'Lacey',
            'Puckett',
            '3001 Knoxville Center Drive',
            'Suite 2294',
            'Knoxville',
            'TN',
            'US United States',
            '37924-5083',
            '8653863481',
            '',
            'Lacey',
            'Puckett',
            '',
            '',
            '',
            '',
            '',
            '',
            '865-386-3481',
        ],
        [
            '298886',
            'Lacey Puckett',
            '',
            'Lacey',
            'Puckett',
            '3001 Knoxville Center Drive',
            'Suite 2294',
            'Knoxville',
            'TN',
            'US United States',
            '37924-5083',
            '8653863481',
            '',
            'Lacey',
            'Puckett',
            '',
            '',
            '',
            '',
            '',
            '',
            '865-386-3481',
        ],
        [
            '298887',
            'Philip Lantz',
            '',
            'Philip',
            'Lantz',
            '200 Braxton Street',
            '',
            'Clarksburg',
            'WV',
            'US United States',
            '26301-2419',
            '6243041099',
            '',
            'Amanda',
            'O\'Keefe',
            '135 Hamilton Ave',
            '',
            'Vandergrift',
            'PA',
            'US United States',
            '15690',
            '7243041090',
        ],
        [
            '298888',
            'Melissa Leichliter',
            '',
            'Melissa',
            'Leichliter',
            '1049 Deleone Drive',
            '',
            'Kent',
            'OH',
            'US United States',
            '44240-2025',
            '2164082909',
            '',
            'Melissa',
            'Leichliter',
            '1049 Deleone Drive',
            '',
            'Kent',
            'OH',
            'US United States',
            '44240',
            '2164082909',
        ],
        [
            '298889',
            'Danielle McClain',
            '',
            'Danielle',
            'McClain',
            '125 Caryota Lane',
            '',
            'Summerville',
            'SC',
            'US United States',
            '29486-5326',
            '9126756776',
            '',
            'Danielle',
            'McClain',
            '1248 McCornack Road',
            '',
            'Wahiawa',
            'HI',
            'US United States',
            '96786',
            '9126756776',
        ],
        [
            '298894',
            'Ashley LaCombe',
            '',
            'Ashley',
            'LaCombe',
            '4101 E Louisiana State Dr',
            '',
            'Kenner',
            'LA',
            'US United States',
            '70065-1703',
            '5043070855',
            '',
            'Ashley',
            'LaCombe',
            '4101 E Louisiana State Dr',
            '',
            'Kenner',
            'LA',
            'US United States',
            '70065-1703',
            '5043070855',
        ],
        [
            '298880',
            'Jean Schebe',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '07013-2695',
            '2015751443',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '7013',
            '2015751443',
        ],
        [
            '298890',
            'David Wiedenbenner',
            '',
            'David',
            'Wiedenbenner',
            '89 Carlton Lane',
            '',
            'Ringgold',
            'GA',
            'US United States',
            '30736-3304',
            '4234880257',
            '',
            'David',
            'Wiedenbenner',
            '89 Carlton Lane',
            '',
            'Ringgold',
            'GA',
            'US United States',
            '30736',
            '4234880257',
        ],
        [
            '165022',
            'Tinesha Carol',
            '',
            'Tinesha',
            'Carol',
            '4600 Josephine Ave',
            '',
            'Beltsville',
            'MD',
            'US United States',
            '20705-2540',
            '2404854069',
            '',
            'Tinesha',
            'Carol',
            '',
            '',
            '',
            '',
            '',
            '',
            '240-485-4069',
        ],
        [
            '298891',
            'Danielle Carman',
            '',
            'Danielle',
            'Carman',
            '2504 W Timberlake Dr',
            '',
            'Lincoln',
            'NE',
            'US United States',
            '68522-9100',
            '2034306988',
            '',
            'Danielle',
            'Carman',
            '2504 W Timberlake Dr',
            '',
            'Lincoln',
            'NE',
            'US United States',
            '68522',
            '2034306988',
        ],
        [
            '298889',
            'Danielle McClain',
            '',
            'Danielle',
            'McClain',
            '125 Caryota Lane',
            '',
            'Summerville',
            'SC',
            'US United States',
            '29486-5326',
            '9126756776',
            '',
            'Danielle',
            'McClain',
            '1248 McCornack Road',
            '',
            'Wahiawa',
            'HI',
            'US United States',
            '96786',
            '9126756776',
        ],
        [
            '298892',
            'PRENTICE L SPREWELL',
            '',
            'PRENTICE L',
            'SPREWELL',
            '6106 Berwood Terr',
            '',
            'East Stroudsburg',
            'PA',
            'US United States',
            '18301-9446',
            '9042074145',
            '',
            'PRENTICE L',
            'SPREWELL',
            '6106 Berwood Terr',
            '',
            'East Stroudsburg',
            'PA',
            'US United States',
            '18301',
            '9042074145',
        ],
        [
            '298838',
            'Donna Summers',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074-9223',
            '7409652132',
            '',
            'Donna',
            'Summers',
            '111 N. Columbus Street',
            '',
            'Sunbury',
            'OH',
            'US United States',
            '43074',
            '7409652132',
        ],
        [
            '296280',
            'Luis Angel',
            '',
            'Luis',
            'Angel',
            '13525  Tenbury Wells Way',
            '',
            'Winter Garden',
            'FL',
            'US United States',
            '34787-4759',
            '3472683779',
            '',
            'Celi',
            'Lebron',
            '51 Buchanan Place Apt.1e',
            '',
            'Bronx',
            'NY',
            'US United States',
            '10453',
            '917-912-1071',
        ],
        [
            '298893',
            'Michael Navia',
            '',
            'Michael',
            'Navia',
            '17111 San Pedro Circle',
            '',
            'Fountain Valley',
            'CA',
            'US United States',
            '92708-3930',
            '7144545824',
            '',
            'Michael',
            'Navia',
            '17111 San Pedro Circle',
            '',
            'Fountain Valley',
            'CA',
            'US United States',
            '92708',
            '7144545824',
        ],
        [
            '236361',
            'Mary Trzcinski',
            '',
            'Mary',
            'Trzcinski',
            '19202 Lake Allen Rd',
            '',
            'LUTZ',
            'FL',
            'US United States',
            '33558-4946',
            '8139494670',
            '',
            'Mary',
            'Trzcinski',
            '19202 Lake Allen Rd',
            '',
            'LUTZ',
            'FL',
            'US United States',
            '33558',
            '8139494670',
        ],
        [
            '290275',
            'Jill Schechter',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
        ],
        [
            '196278',
            'Sarah Wolverton',
            '',
            'Sarah',
            'Wolverton',
            '1336 Stonegate Drve',
            '',
            'Downingtown',
            'PA',
            'US United States',
            '19335',
            '3039032420',
            '',
            'Sarah',
            'Wolverton',
            '1336 Stonegate Drve',
            '',
            'Downingtown',
            'PA',
            'US United States',
            '19335',
            '3039032420',
        ],
        [
            '290680',
            'Josephine Alvarez',
            '',
            'Josephine',
            'Alvarez',
            '741 Flynn Rd',
            '',
            'Camarillo',
            'CA',
            'US United States',
            '93012-8056',
            '8184864755',
            '',
            'Josephine',
            'Alvarez',
            '3128 South N St',
            '',
            'Oxnard',
            'CA',
            'US United States',
            '93033',
            '8184864755',
        ],
        [
            '290680',
            'Josephine Alvarez',
            '',
            'Josephine',
            'Alvarez',
            '741 Flynn Rd',
            '',
            'Camarillo',
            'CA',
            'US United States',
            '93012-8056',
            '8184864755',
            '',
            'Josephine',
            'Alvarez',
            '3128 South N St',
            '',
            'Oxnard',
            'CA',
            'US United States',
            '93033',
            '8184864755',
        ],
        [
            '165022',
            'Tinesha Carol',
            '',
            'Tinesha',
            'Carol',
            '4600 Josephine Ave',
            '',
            'Beltsville',
            'MD',
            'US United States',
            '20705-2540',
            '2404854069',
            '',
            'Tinesha',
            'Carol',
            '',
            '',
            '',
            '',
            '',
            '',
            '240-485-4069',
        ],
        [
            '205151',
            'Hannah Van Buren',
            '',
            'Hannah Van',
            'Buren',
            '1 Williams Street',
            '',
            'Wynantskill',
            'NY',
            'US United States',
            '12198-2815',
            '5186497822',
            '',
            'Hannah',
            'Van Buren',
            '',
            '',
            '',
            '',
            '',
            '',
            '518-649-7822',
        ],
        [
            '298880',
            'Jean Schebe',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '07013-2695',
            '2015751443',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '7013',
            '2015751443',
        ],
        [
            '298895',
            'Lyniece McNair-Levi',
            '',
            'Lyniece',
            'McNair-Levi',
            '2291 Lincoln Manor Drive',
            '',
            'Flint',
            'MI',
            'US United States',
            '48507-4415',
            '2487563197',
            '',
            'Lyniece',
            'McNair-Levi',
            '2291 Lincoln Manor Drive',
            '',
            'Flint',
            'MI',
            'US United States',
            '48507',
            '2487563197',
        ],
        [
            '290275',
            'Jill Schechter',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
        ],
        [
            '298896',
            'Jennifer Piedmonte',
            '',
            'Jennifer',
            'Piedmonte',
            '404 Church Street',
            '',
            'Solvay',
            'NY',
            'US United States',
            '13209-1414',
            '3154918106',
            '',
            'Jennifer',
            'M Piedmonte',
            '',
            '',
            '',
            '',
            '',
            '',
            '315-487-5997',
        ],
        [
            '270999',
            'Daina Russell',
            '',
            'Daina',
            'Russell',
            '251 Foxglove Dr',
            '',
            'Patterson',
            'LA',
            'US United States',
            '70392-5742',
            '9857145111',
            '',
            'Daina',
            'Russell',
            '',
            '',
            '',
            '',
            '',
            '',
            '985-714-5111',
        ],
        [
            '236361',
            'Mary Trzcinski',
            '',
            'Mary',
            'Trzcinski',
            '19202 Lake Allen Rd',
            '',
            'LUTZ',
            'FL',
            'US United States',
            '33558-4946',
            '8139494670',
            '',
            'Mary',
            'Trzcinski',
            '19202 Lake Allen Rd',
            '',
            'LUTZ',
            'FL',
            'US United States',
            '33558',
            '8139494670',
        ],
        [
            '298897',
            'Wesley Johnson',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
        ],
        [
            '298897',
            'Wesley Johnson',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
        ],
        [
            '298898',
            'Laura Page',
            '',
            'Laura',
            'Page',
            '9300 Red Baron Blvd',
            '',
            'Reno',
            'NV',
            'US United States',
            '89506-2973',
            '7757629429',
            '',
            'Laura',
            'Page',
            '9300 Red Baron Blvd',
            '',
            'Reno',
            'NV',
            'US United States',
            '89506',
            '7757629429',
        ],
        [
            '298880',
            'Jean Schebe',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '07013-2695',
            '2015751443',
            '',
            'Jean',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '7013',
            '2015751443',
        ],
        [
            '298899',
            'Erin Isbell (℅ L. Ellis)',
            '',
            'Erin Isbell (℅ L.',
            'Ellis)',
            '115 W. 126th Street #3',
            '',
            'New York',
            'NY',
            'US United States',
            '10027-4548',
            '513-227-3683',
            '',
            'Latosha',
            'Ellis',
            '815 Porter Street',
            'Apt. 308',
            'Richmond',
            'VA',
            'US United States',
            '23224',
            '513-227-3683',
        ],
        [
            '298897',
            'Wesley Johnson',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
        ],
        [
            '298897',
            'Wesley Johnson',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
            '',
            'Wesley',
            'Johnson',
            '1339 Black Willow Trl',
            '',
            'Altamonte Springs',
            'FL',
            'US United States',
            '32714-1151',
            '4073733927',
        ],
        [
            '298900',
            'Mike Aull',
            '',
            'Mike',
            'Aull',
            '301 NE 58th Street',
            '',
            'Oak Island',
            'NC',
            'US United States',
            '28465-4814',
            '9198153903',
            '',
            'Deanna',
            'Wells',
            '2223 Foutz Ave',
            '',
            'San Diego',
            'CA',
            'US United States',
            '92109',
            '9198153903',
        ],
        [
            '290275',
            'Jill Schechter',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
            '',
            'Jill',
            'Schechter',
            '17441 Lull St',
            '',
            'Northridge',
            'CA',
            'US United States',
            '91325-4525',
            '805-444-4877',
        ],
        [
            '298880',
            'Carol Schebe',
            '',
            'Carol',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '07013-2695',
            '2015751443',
            '',
            'Carol',
            'Schebe',
            '6307 HARCOURT RD',
            '',
            'CLIFTON',
            'NJ',
            'US United States',
            '7013',
            '2015751443',
        ],
        [
            '298901',
            'GUY WHETSTONE',
            '',
            'GUY',
            'WHETSTONE',
            '3031 Stillwater Dr',
            '',
            'Kissimmee',
            'FL',
            'US United States',
            '34743-7871',
            '321-284-6067',
            '',
            'GUY',
            'WHETSTONE',
            '3031 Stillwater Dr',
            '',
            'Kissimmee',
            'FL',
            'US United States',
            '34743-7871',
            '321-284-6067',
        ],

    ];

    public function run ()
    {
        foreach ( $this->customers as $value ) {
            // insert customer
            $i = 0;
            $customer = new Customer();
            $customer->customer_id = $value[$i++];
            $customer->ship_full_name = $value[$i++];
            $customer->company_name = $value[$i++];
            $customer->first_name = $value[$i++];
            $customer->last_name = $value[$i++];
            $customer->shipping_address_1 = $value[$i++];
            $customer->shipping_address_2 = $value[$i++];
            $customer->ship_city = $value[$i++];
            $customer->ship_state = $value[$i++];
            $customer->ship_country = $value[$i++];
            $customer->ship_zip = $value[$i++];
            $customer->ship_phone = $value[$i++];
            $customer->bill_company_name = $value[$i++];
            $customer->bill_first_name = $value[$i++];
            $customer->bill_last_name = $value[$i++];
            $customer->bill_address_1 = $value[$i++];
            $customer->bill_address_2 = $value[$i++];
            $customer->bill_city = $value[$i++];
            $customer->bill_state = $value[$i++];
            $customer->bill_country = $value[$i++];
            $customer->bill_zip = $value[$i++];
            $customer->bill_phone = $value[$i++];
            $customer->save();
        }
    }
}
